### ISSUE TITLE
Is this good pattern? TwitterAPI::new_using_env() for light users

### ISSUE THREAD

**Issue by hppRC** [hppRC/kuon#14]
## Example

```rust
use anyhow::Result;

#[tokio::main]
async fn main() -> Result<()> {
    // Please set API_KEY, API_SECRET_KEY, ACCESS_TOKEN, ACCESS_TOKEN_SECRET in your environment
    let api: kuon::TwitterAPI = kuon::TwitterAPI::new_using_env().await?;

    let res: kuon::SearchResult = api.search_tweets("rust").await?;
    for tweet in res.statuses {
        println!("{}", tweet.text);
    }

    Ok(())
}
```

This method uses environment variables of API keys and other credentials.
Using environment variables implicitly is not a good option, however, this pattern provides easy ways to use this library for users. 
Is this method good? Or any other good pattern for light users?

**Comment by magurotuna** [comment]
In my opinion, providing a method like `new_using_env` is not so bad. It would be convenient for users who intend to give it a try.

`new_using_env` will panic if the four required environment variables are not set, so the signature of `new_using_env` should be like `fn new_using_env() -> Result<kuon::TwitterAPI>`.
Besides, it would be necessary to write to the document that `new_using_env` requires the four envs internally and if those are not set then it will return `Err`.

**Comment by hppRC** [comment]
@magurotuna Thanks for your advice!
Ok, then I'll add this method with documents and enough error messages (probably using `thiserror`).
